window.gcexports.globalLexicon = {
    "let" : { "tk": 18, "cls": "keyword" },
    "if" : { "tk": 5, "cls": "keyword" },
    "then" : { "tk": 6, "cls": "keyword" },
    "else" : { "tk": 7, "cls": "keyword" },
    "case" : { "tk": 15, "cls": "keyword" },
    "of" : { "tk": 16, "cls": "keyword" },
    "end" : { "tk": 17, "cls": "keyword", "length": 0 },

    "true" : { "tk": 20, "cls": "val", "length": 0 },
    "false" : { "tk": 20, "cls": "val", "length": 0 },

    "concat" : { "tk": 1, "name": "CONCAT", "cls": "function", "length": 2 , "arity": 2 },
    "equivSyntax" : { "tk": 1, "name": "EQUIV-SYNTAX", "cls": "function", "length": 2 , "arity": 2 },
    "equivLiteral" : { "tk": 1, "name": "EQUIV-LITERAL", "cls": "function", "length": 2 , "arity": 2 },
    "equivSymbolic" : { "tk": 1, "name": "EQUIV-SYMBOLIC", "cls": "function", "length": 2 , "arity": 2 },
    "equivValue" : { "tk": 1, "name": "EQUIV-VALUE", "cls": "function", "length": 2 , "arity": 2 },
    "isFactorised" : { "tk": 1, "name": "IS-FACTORISED", "cls": "function", "length": 1 , "arity": 1 },
    "isSimplified" : { "tk": 1, "name": "IS-SIMPLIFIED", "cls": "function", "length": 1 , "arity": 1 },
    "isExpanded" : { "tk": 1, "name": "IS-EXPANDED", "cls": "function", "length": 1 , "arity": 1 },
    "isUnit" : { "tk": 1, "name": "IS-UNIT", "cls": "function", "length": 2 , "arity": 2 },
    "isTrue" : { "tk": 1, "name": "IS-TRUE", "cls": "function", "length": 1 , "arity": 1 },
    "calculate" : { "tk": 1, "name": "CALCULATE", "cls": "function", "length": 1 , "arity": 1 },
    "translate" : { "tk": 1, "name": "SPEAK", "cls": "function", "length": 2 , "arity": 2 },
    "speak" : { "tk": 1, "name": "SPEAK", "cls": "function", "length": 1 , "arity": 1 },
    "validSyntax" : { "tk": 1, "name": "VALID-SYNTAX", "cls": "function", "length": 1 , "arity": 1 },
    "not" : { "tk": 1, "name": "NOT", "cls": "function", "length": 1 },
    "inverseResult" : { "tk": 1, "name": "NOT", "cls": "function", "length": 1 },
    "allowDecimal" : { "tk": 1, "name": "ALLOW-DECIMAL", "cls": "function", "length": 1 },
    "allowThousandsSeparator" : { "tk": 1, "name": "ALLOW-THOUSANDS-SEPARATOR", "cls": "function", "length": 1 },
    "allowInterval" : { "tk": 1, "name": "ALLOW-INTERVAL", "cls": "function", "length": 1 },
    "ignoreOrder" : { "tk": 1, "name": "IGNORE-ORDER", "cls": "function", "length": 1 },
    "ignoreText" : { "tk": 1, "name": "IGNORE-TEXT", "cls": "function", "length": 1 },
    "ignoreTrailingZeros" : { "tk": 1, "name": "IGNORE-TRAILING-ZEROS", "cls": "function", "length": 1 },
    "ignoreCoefficientOne" : { "tk": 1, "name": "IGNORE-COEFFICIENT-ONE", "cls": "function", "length": 1 },
    "hideExpected" : { "tk": 1, "name": "HIDE-EXPECTED", "cls": "function", "length": 1 },
    "compareSides" : { "tk": 1, "name": "COMPARE-SIDES", "cls": "function", "length": 1 },
    "decimalPlaces" : { "tk": 1, "name": "DECIMAL-PLACES", "cls": "function", "length": 2 },
    "field" : { "tk": 1, "name": "FIELD", "cls": "function", "length": 2 },
    "setDecimalSeparator" : { "tk": 1, "name": "SET-DECIMAL-SEPARATOR", "cls": "function", "length": 2 },
    "setThousandsSeparator" : { "tk": 1, "name": "SET-THOUSANDS-SEPARATOR", "cls": "function", "length": 2 },
    "IN" : { "tk": 1, "name": "IN", "cls": "function", "length": 0 }
}
